[package]
name = "vibird-browser"
version = "1.2.4"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
tauri = { version = "2.0.0", features = ["devtools", "unstable"] }
tauri-plugin-shell = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
rusqlite = { version = "0.31", features = ["bundled"] }
adblock = "0.8"
rmp = "=0.8.11"
url = "2.5"
dirs = "5.0"
log = "0.4"
env_logger = "0.11"
reqwest = { version = "0.12", features = ["json", "stream"] }
argon2 = { version = "0.5", features = ["std"] }
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.22"
zeroize = "1.8"
which = "6.0"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }
